# Generated by Django 5.0.1 on 2024-01-28 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershopbind',
            name='shop_details',
        ),
        migrations.RemoveField(
            model_name='usershopbind',
            name='shop_positions',
        ),
        migrations.RemoveField(
            model_name='usershopbind',
            name='user',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShopModel',
        ),
        migrations.DeleteModel(
            name='ShopPositions',
        ),
        migrations.DeleteModel(
            name='UserShopBind',
        ),
    ]
