# Generated by Django 5.0.1 on 2024-01-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_userinfo_name_alter_userinfo_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
