# Generated by Django 5.0.1 on 2024-01-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_remove_userinfo_name_userinfo_nameing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nameing',
            new_name='name',
        ),
    ]
