# Generated by Django 5.0.1 on 2024-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_rename_nameing_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='power_of_attorney',
            field=models.PositiveIntegerField(default=0, max_length=2),
        ),
    ]
