# Generated by Django 5.0.1 on 2024-01-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_userinfo_power_of_attorney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='power_of_attorney',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='role',
        ),
    ]
