# Generated by Django 5.0.1 on 2024-01-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_userinfo_balance_userinfo_power_of_attorney_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='power_of_attorney',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='role',
        ),
    ]
