# Generated by Django 5.0.1 on 2024-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_remove_userinfo_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
