# Generated by Django 5.0.1 on 2024-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_userinfo_balance_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='Anonymus', max_length=20),
        ),
    ]
